# Generated by Django 3.1.5 on 2021-01-20 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210119_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('contacts', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subrubric')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_timestamp_path)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bulletin')),
            ],
        ),
    ]
